// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raxgcndwtqphoxoagthf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJheGdjbmR3dHFwaG94b2FndGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzAyOTgsImV4cCI6MjA2OTY0NjI5OH0.KTapRHzfDJr3kz2GKIj5U4XlAUUM3_V4mN0aOhO6yug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});